version: '3.8'
services:
  app:
    image: golang:1.21-alpine
    working_dir: /app
    volumes:
      - .:/app
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    ports:
      - "5005:5005"
    environment:
      GOCACHE: /go-cache
    entrypoint:
      - go
      - run
      - .
